### ISSUE TITLE
Kibana 4.4.2 doesn't start with ubuntu 14.04

### ISSUE THREAD

**Issue by cyberflow** [realityforge/chef-kibana#66]
in upstart log:
```
Error: EACCES: permission denied, open '/usr/local/kibana-4.4.2/optimize/.babelcache.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at save (/usr/local/kibana-4.4.2/node_modules/babel-core/lib/api/register/cache.js:35:19)
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickDomainCallback (node.js:385:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:134:18)
    at node.js:962:3
```

**Comment by cyberflow** [comment]
fixed by #61
